package pixi.typings.compressed_textures

import seskar.js.JsInt
import seskar.js.JsString
import seskar.js.JsUnion

@JsUnion
external enum class CompressedTextureExtensionRef {
	@JsString("levelId")
	LEVEL_ID,
	
	@JsString("levelWidth")
	LEVEL_WIDTH,
	
	@JsString("levelHeight")
	LEVEL_HEIGHT,
	
	@JsString("levelBuffer")
	LEVEL_BUFFER
}

@JsUnion
external enum class KEYOF_INTERNAL_FORMATS {
	COMPRESSED_RGB_S3TC_DXT1_EXT,
	COMPRESSED_RGBA_S3TC_DXT1_EXT,
	COMPRESSED_RGBA_S3TC_DXT3_EXT,
	COMPRESSED_RGBA_S3TC_DXT5_EXT,
	COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT,
	COMPRESSED_SRGB_ALPHA_S3TC_DXT3_EXT,
	COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT,
	COMPRESSED_SRGB_S3TC_DXT1_EXT,
	COMPRESSED_R11_EAC,
	COMPRESSED_SIGNED_R11_EAC,
	COMPRESSED_RG11_EAC,
	COMPRESSED_SIGNED_RG11_EAC,
	COMPRESSED_RGB8_ETC2,
	COMPRESSED_RGBA8_ETC2_EAC,
	COMPRESSED_SRGB8_ETC2,
	COMPRESSED_SRGB8_ALPHA8_ETC2_EAC,
	COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2,
	COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2,
	COMPRESSED_RGB_PVRTC_4BPPV1_IMG,
	COMPRESSED_RGBA_PVRTC_4BPPV1_IMG,
	COMPRESSED_RGB_PVRTC_2BPPV1_IMG,
	COMPRESSED_RGBA_PVRTC_2BPPV1_IMG,
	COMPRESSED_RGB_ETC1_WEBGL,
	COMPRESSED_RGB_ATC_WEBGL,
	COMPRESSED_RGBA_ATC_EXPLICIT_ALPHA_WEBGL,
	COMPRESSED_RGBA_ATC_INTERPOLATED_ALPHA_WEBGL,
}

@JsUnion
external enum class INTERNAL_FORMATS {
	@JsInt(33776)
	COMPRESSED_RGB_S3TC_DXT1_EXT,
	
	@JsInt(33777)
	COMPRESSED_RGBA_S3TC_DXT1_EXT,
	
	@JsInt(33778)
	COMPRESSED_RGBA_S3TC_DXT3_EXT,
	
	@JsInt(33779)
	COMPRESSED_RGBA_S3TC_DXT5_EXT,
	
	@JsInt(35917)
	COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT,
	
	@JsInt(35918)
	COMPRESSED_SRGB_ALPHA_S3TC_DXT3_EXT,
	
	@JsInt(35919)
	COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT,
	
	@JsInt(35916)
	COMPRESSED_SRGB_S3TC_DXT1_EXT,
	
	@JsInt(37488)
	COMPRESSED_R11_EAC,
	
	@JsInt(37489)
	COMPRESSED_SIGNED_R11_EAC,
	
	@JsInt(37490)
	COMPRESSED_RG11_EAC,
	
	@JsInt(37491)
	COMPRESSED_SIGNED_RG11_EAC,
	
	@JsInt(37492)
	COMPRESSED_RGB8_ETC2,
	
	@JsInt(37496)
	COMPRESSED_RGBA8_ETC2_EAC,
	
	@JsInt(37493)
	COMPRESSED_SRGB8_ETC2,
	
	@JsInt(37497)
	COMPRESSED_SRGB8_ALPHA8_ETC2_EAC,
	
	@JsInt(37494)
	COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2,
	
	@JsInt(37495)
	COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2,
	
	@JsInt(35840)
	COMPRESSED_RGB_PVRTC_4BPPV1_IMG,
	
	@JsInt(35842)
	COMPRESSED_RGBA_PVRTC_4BPPV1_IMG,
	
	@JsInt(35841)
	COMPRESSED_RGB_PVRTC_2BPPV1_IMG,
	
	@JsInt(35843)
	COMPRESSED_RGBA_PVRTC_2BPPV1_IMG,
	
	@JsInt(36196)
	COMPRESSED_RGB_ETC1_WEBGL,
	
	@JsInt(35986)
	COMPRESSED_RGB_ATC_WEBGL,
	
	@JsInt(35986)
	COMPRESSED_RGBA_ATC_EXPLICIT_ALPHA_WEBGL,
	
	@JsInt(34798)
	COMPRESSED_RGBA_ATC_INTERPOLATED_ALPHA_WEBGL;
}
