package typings.compressed_textures

import typings.Number

external interface WEBGL_compressed_texture_astc {
	fun getSupportedProfiles(): Array<String>
	var COMPRESSED_RGBA_ASTC_10x10_KHR: GLenum
	var COMPRESSED_RGBA_ASTC_10x5_KHR: GLenum
	var COMPRESSED_RGBA_ASTC_10x6_KHR: GLenum
	var COMPRESSED_RGBA_ASTC_10x8_KHR: GLenum
	var COMPRESSED_RGBA_ASTC_12x10_KHR: GLenum
	var COMPRESSED_RGBA_ASTC_12x12_KHR: GLenum
	var COMPRESSED_RGBA_ASTC_4x4_KHR: GLenum
	var COMPRESSED_RGBA_ASTC_5x4_KHR: GLenum
	var COMPRESSED_RGBA_ASTC_5x5_KHR: GLenum
	var COMPRESSED_RGBA_ASTC_6x5_KHR: GLenum
	var COMPRESSED_RGBA_ASTC_6x6_KHR: GLenum
	var COMPRESSED_RGBA_ASTC_8x5_KHR: GLenum
	var COMPRESSED_RGBA_ASTC_8x6_KHR: GLenum
	var COMPRESSED_RGBA_ASTC_8x8_KHR: GLenum
	var COMPRESSED_SRGB8_ALPHA8_ASTC_10x10_KHR: GLenum
	var COMPRESSED_SRGB8_ALPHA8_ASTC_10x5_KHR: GLenum
	var COMPRESSED_SRGB8_ALPHA8_ASTC_10x6_KHR: GLenum
	var COMPRESSED_SRGB8_ALPHA8_ASTC_10x8_KHR: GLenum
	var COMPRESSED_SRGB8_ALPHA8_ASTC_12x10_KHR: GLenum
	var COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR: GLenum
	var COMPRESSED_SRGB8_ALPHA8_ASTC_4x4_KHR: GLenum
	var COMPRESSED_SRGB8_ALPHA8_ASTC_5x4_KHR: GLenum
	var COMPRESSED_SRGB8_ALPHA8_ASTC_5x5_KHR: GLenum
	var COMPRESSED_SRGB8_ALPHA8_ASTC_6x5_KHR: GLenum
	var COMPRESSED_SRGB8_ALPHA8_ASTC_6x6_KHR: GLenum
	var COMPRESSED_SRGB8_ALPHA8_ASTC_8x5_KHR: GLenum
	var COMPRESSED_SRGB8_ALPHA8_ASTC_8x6_KHR: GLenum
	var COMPRESSED_SRGB8_ALPHA8_ASTC_8x8_KHR: GLenum
}

external interface WEBGL_compressed_texture_s3tc {
	var COMPRESSED_RGBA_S3TC_DXT1_EXT: GLenum
	var COMPRESSED_RGBA_S3TC_DXT3_EXT: GLenum
	var COMPRESSED_RGBA_S3TC_DXT5_EXT: GLenum
	var COMPRESSED_RGB_S3TC_DXT1_EXT: GLenum
}

external interface WEBGL_compressed_texture_s3tc_srgb {
	var COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT: GLenum
	var COMPRESSED_SRGB_ALPHA_S3TC_DXT3_EXT: GLenum
	var COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT: GLenum
	var COMPRESSED_SRGB_S3TC_DXT1_EXT: GLenum
}

typealias GLenum = Number
